### ISSUE TITLE
typo in Custom Scorer instructions

### ISSUE THREAD

**Issue by joe4k** [watson-developer-cloud/answer-retrieval#19]
Before you start creating custom scorers, make sure you have created and configured a Solr cluster and trained a ranker by either following the steps on the notebook "Enhanced Retrieval.ipynb" or by using some other tooling 

==> this should reference the "Answer-Retrieval.ipynb" notebook

**Comment by lkrishnamurthy** [comment]
@joe4k : Thanks. Will fix it along with few other issues Javier ran into.
