### ISSUE TITLE
Field Request : Need to show default ranker in the sample app when custom ranker isn't available

### ISSUE THREAD

**Issue by lkrishnamurthy** [watson-developer-cloud/answer-retrieval#22]
Per Swami's request, need to add a toggle button/radio button to show default ranker if no custom ranker is available. This is needed so the UI can show the default ranker and Solr results.

**Comment by lkrishnamurthy** [comment]
1. Need to add an extra method or endpoint in server.py
2. Modify the controller and model with additional method to default ranker
3. Provide an optional radio button in the UI to allow users to switch to default ranker.

**Comment by lkrishnamurthy** [comment]
Fixed the backend to add a new endpoint. 
PR : https://github.com/watson-developer-cloud/answer-retrieval/pull/26

**Comment by lkrishnamurthy** [comment]
UI work to be completed by Abhi. Estimate : 1 day.

**Comment by AbhishekShrivastava** [comment]
As per discussion with Lakshmi, we do need any toggle button or switch at UI. There would be a variable (DEFAULT_RANKER=TRUE) in an environment file which will decide to show the Default or Custom ranker at the UI.

**Comment by lkrishnamurthy** [comment]
Add logic to use an environment variable to switch between default and custom ranker.  No UI changes necessary.  PR  #29
