### ISSUE TITLE
Notebook 2 env file

### ISSUE THREAD

**Issue by jrtorres** [watson-developer-cloud/answer-retrieval#23]
Notebook 2 should mention the need to update the .env file with cluster id & collection name before the generation of training data. Then with the custom ranker id before the experiment step. Also need to restart the flask server after changing the .env file.

**Comment by lkrishnamurthy** [comment]
@jrtorres : This is incorporated last week. Right before running experiments I have added a comment to update the .env file.  Thanks for the valuable feedback.
