### ISSUE TITLE
Answer Retrieval Scripts not supported on Windows PCs

### ISSUE THREAD

**Issue by lkrishnamurthy** [watson-developer-cloud/answer-retrieval#25]
The scripts aren't running on Windows. KPMG had issues on their windows laptop.

**Comment by lkrishnamurthy** [comment]
1. Need to make sure the scripts are compatible for running on Windows else need separate scripts.
2. Notebooks should be tested for folders and path. Should include path.separator() like methods where applicable.
3. Documentation should include install pre-reqs (cygwin etc) for windows users.

**Comment by germanattanasio** [comment]
@lkrishnamurthy you can make the bash script to be python scripts and that will make your life easier

**Comment by lkrishnamurthy** [comment]
@germanattanasio : Like the idea on making the bash scripts into python. It will be a major refactoring that need to be sized.
