### ISSUE TITLE
Running Python "server.py" Fails

### ISSUE THREAD

**Issue by Hmaal** [watson-developer-cloud/answer-retrieval#34]
After following the steps as directed in the markdown, getting to and running the Python server "python server.py" fails and displays an error.

XXX-XXX-XXX:answer-retrieval hmaal$ python server.py
Traceback (most recent call last):
  File "server.py", line 26, in <module>
    from retrieve_and_rank_scorer.scorers import Scorers
  File "/Users/hmaal/anaconda3/lib/python3.5/site-packages/retrieve_and_rank_scorer/scorers.py", line 77
    except futures.TimeoutError, e:
                               ^
SyntaxError: invalid syntax

**Comment by lkrishnamurthy** [comment]
It looks like you are running this on Python 3.5. 3.5 is not supported for this starter kit. Recommend you following the pre-requisite steps in the README to install Anaconda / 2.7.X version
