### ISSUE TITLE
Error message mockup

### ISSUE THREAD

**Issue by dezzie** [watson-developer-cloud/answer-retrieval#4]
@germanattanasio and @jzhang300 asked for a way to display errors in sample apps:

Here ya go:
![screen shot 2016-07-18 at 5 05 43 pm](https://cloud.githubusercontent.com/assets/1301932/16932096/ef72c2f6-4d09-11e6-85b2-6b531089f131.png)
API Reference: http://www.ibm.com/watson/developercloud/retrieve-and-rank/api/v1/
Submit Issue: https://github.com/watson-developer-cloud/answer-retrieval/issues

Barebones:
![screen shot 2016-07-18 at 5 09 27 pm](https://cloud.githubusercontent.com/assets/1301932/16932183/68b2dd22-4d0a-11e6-85d2-00e3f367dad8.png)

**Comment by jzhang300** [comment]
@dezzie Both designs look good to me, the buttons one is easier on the eyes.  The only thing I'm not sure of is the "source" property?

**Comment by dezzie** [comment]
If there isn't a source, that's fine, you can take it out. I'm following what the Analytics team is using for its pattern library ^_^

**Comment by germanattanasio** [comment]
I'm assigning this to @lkrishnamurthy, this team maintain this project

**Comment by lkrishnamurthy** [comment]
I am ok with the design. Agree with German on the source field. One thing with this app, is that it make two calls. One to Solr and one to a custom ranker. Either one of them could be throwing errors. Wonder if the source column can be effectively re-purposed for that. @dezzie : thoughts?

**Comment by dezzie** [comment]
@lkrishnamurthy @germanattanasio I reached out to people and turns out that's what the source field was for all along. Works out!
